language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XmbFc9K6+s4+D/iKhIr4WDccMVJzaGtzCopoeYiypGV0ehcOv55pD4gyVPfEKMr8ate4acxg1iGPboUcCy9c2TlQvKoRq7vcD/D8eumgaKxbNJLBphIYCwiqx6thVQzNXL0wUNDTkXkMiXQYfASyA7eZVlDDHgdsYg5r8kPCv7P5p7Y5KpawM1jnd12Qe/0muOe5DSnjbdx+m0LlbOu3uaRFa1N0/aolsErcYHAqAUfha2nJjB0aXuOJjZrsGRDZr81HrNKokikhxfYPzBf/nitZHSLA6rIvHopA2QwyHJYWiMFiGKOq5zSjIfOAQQOtOPIugR/4ujb4jMQQ2ZRZSFjPvUTr6ku2Fmlz2XRUOVT3aTMIJKosCvALMdljaTjlKUfOO3Yd7KAlzAGt/ODmtA7CNvg9dSLEuG7R7Dy9zErvXqoskl+QWMuce5AJwPAP5pB7+/RT+JCjltphqmu+3PJwOjUzTwGn20WSsZuRFcOIb/Xsksh/mkFNil5KbCW8LejBQ+JFYDnzE59YlXPRsE08fudJwYpbvWZvP5KyGtUARcSRXmngRIvzpUQHmJAne4APQZR7UMOmDNXDZ1ZvYqsvEdRlX9HahgNQ2kXDAJYRLK+t/M5YV+vmEqJCNKgD0/0r9kX3ZufvfscjH/c1oTryokOF5Ns8up+ltriesaM=
  file:
    - "state-toggle.js"
    - "state-toggle.min.js"
  on:
    tags: true
